// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDOfXs6XiZyrTM1wDQ-rwNMAm94_Hw1w',
    appId: '1:769291960577:web:774fb80eacd56bc3005b00',
    messagingSenderId: '769291960577',
    projectId: 'playtomicappfirebase',
    authDomain: 'playtomicappfirebase.firebaseapp.com',
    storageBucket: 'playtomicappfirebase.appspot.com',
    measurementId: 'G-WNM7K8V2NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9lGo1n7V7rXljANc9e_yRWOhp8-B940',
    appId: '1:769291960577:android:116a28e1e55467e7005b00',
    messagingSenderId: '769291960577',
    projectId: 'playtomicappfirebase',
    storageBucket: 'playtomicappfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QBBuMhFmeEuTE0VNw-9EB9siHHLoL0Q',
    appId: '1:769291960577:ios:8d7c2e8be3982a71005b00',
    messagingSenderId: '769291960577',
    projectId: 'playtomicappfirebase',
    storageBucket: 'playtomicappfirebase.appspot.com',
    iosBundleId: 'com.example.playtomicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QBBuMhFmeEuTE0VNw-9EB9siHHLoL0Q',
    appId: '1:769291960577:ios:b3ea7a95f608e8c7005b00',
    messagingSenderId: '769291960577',
    projectId: 'playtomicappfirebase',
    storageBucket: 'playtomicappfirebase.appspot.com',
    iosBundleId: 'com.example.playtomicApp.RunnerTests',
  );
}
